"""Create order table

Revision ID: 7fb78bd20ff4
Revises: 92fa472b4c24
Create Date: 2024-06-15 00:22:08.394916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fb78bd20ff4"
down_revision: Union[str, None] = "92fa472b4c24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "promocode")
    op.add_column("orders", sa.Column("promocode", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "promocode")
    op.add_column("orders", sa.Column("promocode", sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
