"""foreign relations

Revision ID: 54c1be4a9b97
Revises: de078a50572b
Create Date: 2024-06-13 10:45:43.681292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54c1be4a9b97"
down_revision: Union[str, None] = "de078a50572b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("used_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "posts", "users", ["used_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "used_id")
    # ### end Alembic commands ###
